# ==========================================
# KONSTANTA FISIKA & PARAMETER PLTU 300 MW
# ==========================================

LHV_COAL = 17.5
FURNACE_EFF = 0.88
MAX_COAL_FEED = 220.0

BOILER_MASS = 50000.0
# [CRITICAL FIX] Menggunakan 0.5 untuk merepresentasikan thermal inertia gabungan baja & air
CP_BOILER = 0.5         
NOMINAL_TEMP = 540.0
NOMINAL_PRESSURE = 165.0

ENTHALPY_FEED_WATER = 0.167
ENTHALPY_STEAM_OUT = 3.456
ENTHALPY_RISE = ENTHALPY_STEAM_OUT - ENTHALPY_FEED_WATER

VALVE_CV = 28.0
TURBINE_EFF = 0.85
ENTHALPY_DROP_NOMINAL = 1.293
GENERATOR_EFF = 0.98

OPTIMAL_AFR = 4.5
MAX_AIR_SUPPLY_KGS = 0.5
MAX_FEEDWATER_RATE_KGS = 350.0

CAUTION_TEMP = 560.0
CAUTION_PRESS = 185.0
# [MEDIUM FIX] Margin level air diperketat agar lebih realistis
CAUTION_LEVEL_LOW = 45.0  
CAUTION_LEVEL_HIGH = 80.0 

FATAL_TEMP = 650.0       
FATAL_PRESS = 220.0      
FATAL_LEVEL_LOW = 15.0   
FATAL_LEVEL_HIGH = 90.0